#!/bin/bash

# Formatting HDFS
hadoop namenode -format

# Running services
/usr/local/hadoop/bin/start-all.sh

# Load data in HDFS
hadoop dfs -copyFromLocal /home/hduser/Shopify/creditcard/data.txt logreg/data.txt

# Check load was successful
/usr/local/hadoop/bin/hadoop dfs -ls logreg

# Run MapReduce job through Hadoop Streaming
hadoop jar /usr/local/hadoop/bin/hadoop-streaming-1.2.1.jar \
   -mapper "python /home/hduser/Shopify/creditcard/mapper.py" \
   -reducer "python /home/hduser/Shopify/creditcard/reducer.py" \
   -input "logreg/data.txt" \
   -output "logreg/output" \
   -file "/home/hduser/Shopify/creditcard/utilities.py"

# Retrieving results
hadoop dfs -get logreg/output/part-00000 /home/hduser/Shopify/creditcard

# Deleting output from HDFS
hadoop dfs -rmr logreg/output